parameters:
#    siny_daemon.example.class: Siny\DaemonBundle\Example

services:
#    siny_daemon.example:
#        class: %siny_daemon.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
